esphome:
  name: wavinahc9000v3
  friendly_name: wavinahc9000v3

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: esphome/components
    components: [wavin_ahc9000]

logger:
  level: DEBUG
  logs:
    wavin_ahc9000: DEBUG

uart:
  id: uart_wavin
  # Prefer stable UART pins (e.g. 16/17) to avoid strapping pin issues
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 38400
  stop_bits: 1
  parity: NONE

wavin_ahc9000:
  id: wavin
  uart_id: uart_wavin
  update_interval: 5s
  allow_mode_writes: false
  # Auto-generate entities
  auto_climates: true
  temperature_sensors: true
  battery_sensors: true
  auto_channels: all
  name_prefix: "Zone "

climate: []

sensor: []

api:
  services:
    - service: wavin_strict_heat
      variables:
        channel: int
      then:
        - lambda: |-
            // Force baseline 0x4000 on the selected channel
            id(wavin).normalize_channel_config(channel, false);

wifi:
  ssid: "<your-ssid>"
  password: "<your-password>"

ota:
