esphome:
  name: wavinahc9000v3
  friendly_name: wavinahc9000v3

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: esphome/components
    components: [wavin_ahc9000]

logger:
  level: DEBUG
  logs:
    wavin_ahc9000: DEBUG

uart:
  id: uart_wavin
  # Prefer stable UART pins (e.g. 16/17) to avoid strapping pin issues
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 38400
  stop_bits: 1
  parity: NONE

wavin_ahc9000:
  id: wavin
  uart_id: uart_wavin
  # Regular polling interval; optionally lower temporarily for quicker discovery
  update_interval: 5s
  # Optional: speed up initial discovery (uncomment briefly)
  # poll_channels_per_cycle: 8
  # update_interval: 2s
  allow_mode_writes: false

# Onboarding helpers (optional): include the chunked YAML tools package
# This adds text sensors and services to generate/publish YAML chunks for HA Jinja stitching.
# Enable during setup, then remove to keep your config clean.
#
# Option A — include from GitHub (recommended):
# packages:
#   wavin_yaml_tools:
#     url: https://github.com/heinekmadsen/esphome_wavinahc9000v3
#     ref: main     # or switch to 'restart' while testing this branch
#     files:
#       - packages/wavin_yaml_tools.yaml
#     refresh: 1d
#
# Option B — include local file (if you cloned the repo):
# packages:
#   wavin_yaml_tools: !include packages/wavin_yaml_tools.yaml

climate:
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Zone 1"
    channel: 1
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Living Area"
    members: [2,3]

sensor:
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Zone 1 Battery"
    channel: 1
    type: battery
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Zone 1 Temperature"
    channel: 1
    type: temperature

# Optional: comfort & standby (eco) setpoint number entities per channel (new)
# number:
#   - platform: wavin_ahc9000
#     wavin_ahc9000_id: wavin
#     channel: 1
#     type: comfort
#     name: "Zone 1 Comfort Setpoint"
#   - platform: wavin_ahc9000
#     wavin_ahc9000_id: wavin
#     channel: 1
#     type: standby
#     name: "Zone 1 Standby Setpoint"

# NOTE: The text_sensor/api helpers below are also provided by the optional package
# at packages/wavin_yaml_tools.yaml. If you enable the package, you can remove
# the following text_sensor/api sections.

api:
  services:
    - service: wavin_strict_heat
      variables:
        channel: int
      then:
        - lambda: |-
            // Force baseline 0x4000 on the selected channel
            id(wavin).normalize_channel_config(channel, false);

wifi:
  ssid: "<your-ssid>"
  password: "<your-password>"

ota:
